# версия синтаксиса
version: '3'

# в этом блоке мы описываем контейнеры, которые будут запускаться
services:
  workspace:
    build: docker/php
    container_name: console_ws
    volumes:
      - .:/data/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge